name: CI Testing Primary Language
on: [push]

jobs:
  read_type:
    runs-on: ubuntu-latest
    name: Detect Primary Language
    steps:
      - name: Checkout
        uses: keyfactor/checkout@v4
        with:
          token: ${{ secrets.V2BUILDTOKEN}}
      - name: Read integration_type
        id: read
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.V2BUILDTOKEN}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.read.outputs.primary_language}} | tee -a $GITHUB_STEP_SUMMARY


