name: CI Testing Primary Language
on: [push]

jobs:
  read_type:
    runs-on: ubuntu-latest
    name: Detect Primary Language
    steps:
      # To use this repository's private action,
      # you must check out the repository
      # Temporarily public, testing in personal Org
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT}}
      - name: Read integration_type
        id: read
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GH_PAT}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.read.outputs.primary_language}} | tee -a $GITHUB_STEP_SUMMARY


